version: 0.2

env:
  variables:
    EnvironmentName: "${EnvironmentName}"
    EC2InstanceType: "${EC2InstanceType}"
    MachineID: "${MachineID}"
    PROJECT_TAG: "${PROJECT_TAG}"
phases:
  install:
    commands:
      - echo Entered the install phase
      # - sudo apt-get update
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install --update
      - aws --version
      - echo Finished installing
    finally:
      - echo Install phase done
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase"
      - echo env-name $EnvironmentName cost $CostGroup
      - echo "Starting cloudformation deployment"
      - aws cloudformation deploy --template-file web-server.yml --tags project="${PROJECT_TAG}" --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region us-east-1 --stack-name "${EnvironmentName}-${CODEBUILD_BUILD_NUMBER}" --parameter-overrides EnvironmentName="${EnvironmentName}" EC2InstanceType="${EC2InstanceType}" MachineID="${MachineID}"
      - echo deployment successful
    finally:
      - echo This always runs even if the install command fails
