version: 0.2

env:
  variables:
    EnvironmentName: "${EnvironmentName}"
    CostGroup: "${CostGroup}"
phases:
  install:
    commands:
      - echo Entered the install phase
      - echo costgroup ${CostGroup}
      # - sudo apt-get update
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install --update
      - aws --version
      - echo Finished installing
    finally:
      - echo Install phase done
  build:
    on-failure: ABORT
    commands:
      - echo "Entered the build phase"
      - echo env-name $EnvironmentName cost $CostGroup
      - echo "Starting cloudformation deployment"
      - aws cloudformation create-stack --template-body vpc-template-1.yml --tags project="${PROJECT_TAG}" --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region us-east-1 --stack-name "ui-${CODEBUILD_BUILD_NUMBER}" --parameters file://network-params.json
      - echo deployment successful
    finally:
      - echo This always runs even if the install command fails
